services:
  finance-service:
    build: ./app
    volumes:
      - "./config:/config"
    ports:
      - "5000:5000"
    networks:
      - backend

  db:
    image: postgres:latest
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "db-volume:/var/lib/postgres"
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password  # Change this to match your actual password
    networks:
      - backend

volumes:
  db-volume:

networks:
  backend:
